version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install AWS Tools
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install awscli==1.14.50
      - run:
          name: Build Docker Image
          command: |
            docker build -t ecr-ci .
      - run:
          name: Push Docker Image
          command: |
            GIT_TAG=$(git describe --tags --always)
            $(aws ecr get-login --no-include-email)
            docker tag responder $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ecr-ci:$GIT_TAG
            docker tag responder $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ecr-ci:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ecr-ci:$GIT_TAG
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ecr-ci:latest

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master


